<a href="https://colab.research.google.com/github/harshadhosewann/Data-Analytics/blob/main/Data_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
import pandas as pd
df = pd.read_csv("data.csv")

In [45]:
df.dtypes

Country       object
Age          float64
Salary       float64
Purchased     object
dtype: object

In [46]:
X = df.iloc[:,:-1].values
Y = df.iloc[:,-1].values 

In [47]:
X

array([['France ', 44.0, 72000.0],
       ['Spain', 27.0, 50000.0],
       ['Germany', 30.0, 60000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France ', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France ', 8.0, 79000.0],
       ['Germany', 50.0, 87000.0],
       ['France ', 37.0, 67000.0]], dtype=object)

In [48]:
Y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

**Encoding categorical data**

**Encoding the independent data**




In [49]:
import numpy as np
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan , strategy = "mean")
imputer.fit(X[:,1:3])
X[:,1:3] = imputer.transform(X[:,1:3])

In [50]:
X

array([['France ', 44.0, 72000.0],
       ['Spain', 27.0, 50000.0],
       ['Germany', 30.0, 60000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 65111.11111111111],
       ['France ', 35.0, 58000.0],
       ['Spain', 34.333333333333336, 52000.0],
       ['France ', 8.0, 79000.0],
       ['Germany', 50.0, 87000.0],
       ['France ', 37.0, 67000.0]], dtype=object)

**Encoding the dependent variable** 


In [51]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
Y = le.fit_transform(Y)

In [52]:
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [53]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers= [("encoder",OneHotEncoder(),[0])], remainder = "passthrough")
X = np.array(ct.fit_transform(X))

In [54]:
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 50000.0],
       [0.0, 1.0, 0.0, 30.0, 60000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 65111.11111111111],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 34.333333333333336, 52000.0],
       [1.0, 0.0, 0.0, 8.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 87000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [55]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y)

In [56]:
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

**Splitting the dataset into Training set and Test set**

In [57]:
from sklearn.model_selection import train_test_split 
X_train, X_test, Y_train, Y_test =  train_test_split(X,Y,test_size = 0.2, random_state = 1)

In [58]:
X_train

array([[0.0, 0.0, 1.0, 34.333333333333336, 52000.0],
       [0.0, 1.0, 0.0, 40.0, 65111.11111111111],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 0.0, 1.0, 27.0, 50000.0],
       [1.0, 0.0, 0.0, 8.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 87000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0]], dtype=object)

In [59]:
X_test

array([[0.0, 1.0, 0.0, 30.0, 60000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [60]:
Y_train

array([0, 1, 0, 0, 1, 1, 0, 1])

In [61]:
Y_test

array([0, 1])

**Features Scaling**

In [62]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,3:] = sc.fit_transform(X_train[:,3:])
X_test = sc.transform(X_test[:,3:])

In [63]:
X_train

array([[0.0, 0.0, 1.0, -0.01751563311064678, -1.1099447448317599],
       [0.0, 1.0, 0.0, 0.45890958749894006, -0.03308160082232404],
       [1.0, 0.0, 0.0, 0.7952097432233544, 0.5327278477250068],
       [0.0, 0.0, 1.0, 0.29075950963673286, -0.37074207818121485],
       [0.0, 0.0, 1.0, -0.6340659186054066, -1.2742120040874365],
       [1.0, 0.0, 0.0, -2.231491658296375, 1.1076632551198753],
       [0.0, 1.0, 0.0, 1.299659976809976, 1.7647322921425819],
       [1.0, 0.0, 0.0, 0.03853439284342208, -0.6171429670647298]],
      dtype=object)

In [64]:
X_test

array([[-0.3818408 , -0.45287571],
       [ 0.20668447,  0.1220597 ]])